In [44]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [45]:
df = pd.read_excel(r"C:\Users\hp\Desktop\player_data.xlsx")
df.head()

Player ID Date Joined  Frequency of Login in a week  \
0     1346.0  2022-04-01                           2.0   
1     2326.0  2023-10-19                           4.0   
2      932.0  2022-12-09                           4.0   
3      845.0  2022-12-05                           5.0   
4      710.0  2023-10-31                           3.0   

   Total Playtime (minutes) Matches Played in  week  Matches Won in a week  \
0                      41.0                       4                    3.0   
1                      33.0                       4                    1.0   
2                      33.0                       5                    4.0   
3                      50.0                      10                    1.0   
4                      30.0                       7                    3.0   

   Matches Lost in a week  Win Rate (%)  Current Rank  No of Cards Owned  \
0                     1.0     75.000000          53.0                2.0   
1                     3.0     25.000000         138.0                9.0   
2                     1.0     80.000000          42.0                2.0   
3                     9.0     10.000000         162.0                4.0   
4                     4.0     42.857143         111.0               11.0   

   Total Gold Coins Owned  inventory purchase in a week retention  
0                     4.0                           3.0       Low  
1                     0.0                           3.0       Low  
2                    15.0                           2.0       Low  
3                    17.0                           3.0       Low  
4                    20.0                           2.0       Low

In [46]:
df.isnull().sum()

Player ID                       4
Date Joined                     4
Frequency of Login in a week    4
Total Playtime (minutes)        4
Matches Played in  week         3
Matches Won in a week           4
Matches Lost in a week          4
Win Rate (%)                    4
Current Rank                    4
No of Cards Owned               4
Total Gold Coins Owned          4
inventory purchase in a week    4
retention                       4
dtype: int64

In [47]:
df = df.dropna()
df.isnull().sum()

Player ID                       0
Date Joined                     0
Frequency of Login in a week    0
Total Playtime (minutes)        0
Matches Played in  week         0
Matches Won in a week           0
Matches Lost in a week          0
Win Rate (%)                    0
Current Rank                    0
No of Cards Owned               0
Total Gold Coins Owned          0
inventory purchase in a week    0
retention                       0
dtype: int64

In [48]:
df['retention'].unique()

array(['Low', 'High'], dtype=object)

In [49]:
df['target'] = df['retention'].map({'Low':0,'High':1})
df.head()

Player ID Date Joined  Frequency of Login in a week  \
0     1346.0  2022-04-01                           2.0   
1     2326.0  2023-10-19                           4.0   
2      932.0  2022-12-09                           4.0   
3      845.0  2022-12-05                           5.0   
4      710.0  2023-10-31                           3.0   

   Total Playtime (minutes) Matches Played in  week  Matches Won in a week  \
0                      41.0                       4                    3.0   
1                      33.0                       4                    1.0   
2                      33.0                       5                    4.0   
3                      50.0                      10                    1.0   
4                      30.0                       7                    3.0   

   Matches Lost in a week  Win Rate (%)  Current Rank  No of Cards Owned  \
0                     1.0     75.000000          53.0                2.0   
1                     3.0     25.000000         138.0                9.0   
2                     1.0     80.000000          42.0                2.0   
3                     9.0     10.000000         162.0                4.0   
4                     4.0     42.857143         111.0               11.0   

   Total Gold Coins Owned  inventory purchase in a week retention  target  
0                     4.0                           3.0       Low       0  
1                     0.0                           3.0       Low       0  
2                    15.0                           2.0       Low       0  
3                    17.0                           3.0       Low       0  
4                    20.0                           2.0       Low       0

In [50]:
df_train, df_test = train_test_split(df,test_size = 0.25)

In [51]:
df_train.shape

(150, 14)

In [52]:
df_test.shape

(50, 14)

In [53]:
df_train.head()

Player ID Date Joined  Frequency of Login in a week  \
157     1966.0  2022-10-02                           5.0   
86       997.0  2022-02-08                           7.0   
95      1686.0  2022-05-22                           4.0   
189     2274.0  2022-11-16                           1.0   
104     2321.0  2022-12-08                           3.0   

     Total Playtime (minutes) Matches Played in  week  Matches Won in a week  \
157                      27.0                      24                    0.0   
86                       58.0                      17                    4.0   
95                       43.0                      11                    0.0   
189                      23.0                       6                    0.0   
104                      30.0                      22                   16.0   

     Matches Lost in a week  Win Rate (%)  Current Rank  No of Cards Owned  \
157                    24.0      0.000000         177.0                4.0   
86                     13.0     23.529412         143.0                5.0   
95                     11.0      0.000000         177.0                8.0   
189                     6.0      0.000000         177.0               15.0   
104                     6.0     72.727273          57.0                7.0   

     Total Gold Coins Owned  inventory purchase in a week retention  target  
157                     4.0                           3.0       Low       0  
86                      2.0                           5.0      High       1  
95                     17.0                           0.0       Low       0  
189                     6.0                           1.0       Low       0  
104                     8.0                           3.0       Low       0

In [54]:
X_train = df_train.drop(columns = ['retention', 'target','Player ID','Date Joined']).values

In [55]:
X_train

array([[5.0, 27.0, 24, ..., 4.0, 4.0, 3.0],
       [7.0, 58.0, 17, ..., 5.0, 2.0, 5.0],
       [4.0, 43.0, 11, ..., 8.0, 17.0, 0.0],
       ...,
       [3.0, 49.0, 15, ..., 0.0, 12.0, 4.0],
       [1.0, 23.0, 4, ..., 0.0, 14.0, 1.0],
       [2.0, 26.0, 22, ..., 5.0, 9.0, 3.0]], dtype=object)

In [56]:
y_train = df_train['target'].values

In [57]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [58]:
model = LogisticRegression()

In [59]:
model.fit(X_train, y_train)

C:\Users\hp\anaconda3\anaconda\envs\newenv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [60]:
X_test = df_test.drop(columns = ['retention', 'target','Player ID','Date Joined']).values

In [61]:
y_test = df_test['target'].values

In [63]:
y_pred = model.predict(X_test)

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1], dtype=int64)